### ISSUE TITLE
Please deploy updated npm module

### ISSUE THREAD

**Issue by sergeychernyshev** [okonet/attr-accept#17]
It looks like the code in the repo was updated since 2016 (in particular ES6 babel config fixed Babel 5 deprecation).

But npm module is still 1.1.0:
https://www.npmjs.com/package/attr-accept

Please deploy a new version to npm

**Comment by idobh2** [comment]
👍 
or at least push a "version" field into the package.json so we can install from this git repo? :)
@okonet

**Comment by schnubor** [comment]
+1, this old babelrc is causing more trouble than it should...

**Comment by SecretLaboratory** [comment]
Yeah threw me for a loop as well yesterday. Ended up quick fixing it by editing the babelrc within the node_modules file (i know, bad practice) and removing the stage 1 stuff. Seemed to compile after that

**Comment by agentilela** [comment]
`"postinstall": "rimraf ./node_modules/attr-accept/.babelrc"`

Feels bad man

**Comment by okonet** [comment]
I don't have much time to maintain this module and would love to get some help. If anyone of you would like to become a maintainer, I can either transfer the ownership (not sure how this is gonna help with nom, though) or add you as a collaborator.

The simples way to make deployments easier would be to use [semantic-release](https://github.com/semantic-release). I also can accept a PR that integrates it (ideally using https://github.com/sapegin/mrm-tasks/tree/master/packages/mrm-task-semantic-release)

**Comment by ajsharp** [comment]
@okonet I'm sure anyone on this thread would be willing to help as a contributor on this repo, at the very least to get a release pushed out. I'm certainly willing to help push a release out if you want to add me as a contributor. Thanks.

**Comment by okonet** [comment]
So I spent an hour trying fixing the build but no luck. Anyone? 

https://travis-ci.org/okonet/attr-accept/jobs/337957145

The build [worked](https://travis-ci.org/okonet/attr-accept/builds/275347739) on the PR and when broke when I merged the PR back to master. Ideas?

**Comment by okonet** [comment]
@ajsharp you should now have push rights for this repo, so I'd appreciate you taking care of this since I don't have time anymore to fix npm issues.

**Comment by ajsharp** [comment]
@okonet I spent some time yesterday as well, trying to get this project to build with react-dropzone, with no luck. If anyone else has any ideas or working forks, I'll happily accept PRs. 

cc @SecretLaboratory @agentilela

**Comment by okonet** [comment]
Not quite sure what it has to do with React-dropzone problem, though. Dropzone already has this package in the bundle so you don’t need to build it anyways

**Comment by ajsharp** [comment]
@okonet Yea, I'm not sure what the issue is either. But when I try to add attr-accept HEAD to react-dropzone (`yarn add okonet/attr-accept#master`) I get a build error:

```
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@7.1.2" has unmet peer dependency "webpack@2 || 3".
warning "react-styleguidist > html-webpack-plugin@2.30.1" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "react-styleguidist > react-docgen-displayname-handler@1.0.0" has incorrect peer dependency "react-docgen@2.x".
warning "react-styleguidist > uglifyjs-webpack-plugin@1.0.0-beta.2" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "react-styleguidist > webpack-dev-server@2.7.1" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "react-styleguidist > webpack-dev-server > webpack-dev-middleware@1.12.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ attr-accept@1.1.0
$ npm run build && npm run test:umd && npm run test:es

> react-dropzone@0.0.0-development build /Users/ajsharp/code/react-dropzone
> npm run clean && npm run build:umd && npm run build:es


> react-dropzone@0.0.0-development clean /Users/ajsharp/code/react-dropzone
> rimraf ./dist


> react-dropzone@0.0.0-development build:umd /Users/ajsharp/code/react-dropzone
> cross-env NODE_ENV=production webpack -p

Hash: b26885bed1c400a0030e
Version: webpack 3.5.5
Time: 993ms
   Asset     Size  Chunks             Chunk Names
index.js  92.7 kB       0  [emitted]  main
   [0] ./src/index.js 20.6 kB {0} [built]
   [3] ./src/utils/index.js 2.01 kB {0} [built]
   [4] ./src/utils/styles.js 511 bytes {0} [built]
    + 2 hidden modules

ERROR in ./src/utils/index.js
Module not found: Error: Can't resolve 'attr-accept' in '/Users/ajsharp/code/react-dropzone/src/utils'
 @ ./src/utils/index.js 13:18-40
 @ ./src/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-dropzone@0.0.0-development build:umd: `cross-env NODE_ENV=production webpack -p`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-dropzone@0.0.0-development build:umd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajsharp/.npm/_logs/2018-02-06T20_57_22_929Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-dropzone@0.0.0-development build: `npm run clean && npm run build:umd && npm run build:es`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-dropzone@0.0.0-development build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajsharp/.npm/_logs/2018-02-06T20_57_22_950Z-debug.log
error Command failed with exit code 2.
```

I wonder if this build error is in any way related to the CI build errors.

**Comment by okonet** [comment]
And why are you adding it from GitHub?

**Comment by ajsharp** [comment]
I'm having issues with the babel 5 presets used in attr-accept 1.1.0.

So I'm trying to test attr-accept#HEAD to prepare the next release of this repo (1.1.1) to make sure it will work with react-dropzone.

I'm not super familiar with how yarn and npm work in terms of building dependencies. I dunno if adding from github runs the build scripts with different settings? However, I can cd into react-dropzone's node_modules copy of attr-accept and build the project fine (the dist/index.js output looks correct). 

Is it common in open source node projects to ignore the compiled output in source control?

**Comment by ajsharp** [comment]
@okonet FWIW, I tried this with a published npm package and I get the same error when trying to build with react-dropzone (`yarn add ajsharp-attr-accept`).

Maybe the issue is some incompatibility between their babelrc files?

**Comment by ajsharp** [comment]
Scratch that, it looks like the build actually does complete successfully. I was including the old package name 🤦‍♂️ .

I'm going to push 1.1.1 with the following commits:

* ecf4526
* 99be4eb

@okonet I probably need to be added to the npm project somehow, right?

**Comment by okonet** [comment]
No, it is using semantic release. All commits are in place. Please see Travis logs

**Comment by okonet** [comment]
And please don’t add version to package.json

**Comment by okonet** [comment]
@ajsharp sorry but I had to remove you from collaborators for now. Commiting to master without code review isn’t helpful. If anyone knows how to resolve the CI issue please fork and submit a PR.

**Comment by rkmarks** [comment]
@okonet I'd be happy to give it a review as well. I've already forked and will check it out.

**Comment by rkmarks** [comment]
@okonet  is this necessary in the .babelrc file? 

https://github.com/okonet/attr-accept/blob/master/.babelrc#L6

could not find anything babel doc related to this

**Comment by ajsharp** [comment]
@okonet Understood. I wasn't aware of a protocol in place for how things are done in this repo, and I got the impression from your previous comments that you don't have the time to oversee it.

I'm happy to follow a pull request / code review model, but I was operating under the assumption that I would be the only one reviewing the code ;) I'm happy to continue to try to help by forking / submitting PRs. 

> And please don’t add version to package.json

Can you explain this? Not having it breaks adding this as a git dep via yarn, and AFAIK is the npm recommended way to track the version.

**Comment by okonet** [comment]
We don’t track versions manually. Instead I’m using semantic-release. You still didn’t answer why you need to add it as a git dependency. Version should be actually set to `0.0.0-development`. If it’s not please feel free to create a PR.

**Comment by okonet** [comment]
@ajsharp feel free to submit a PR if you know how to fix the issue with the CI.

**Comment by ajsharp** [comment]
> You still didn’t answer why you need to add it as a git dependency.

The published version of this repo breaks a project of mine using [parcel](https://github.com/parcel-bundler/parcel). It has something to do with this project's .babelrc settings. So, as a workaround, I was trying to fork react-dropzone and this project to try to fix these issues on my fork of this project. Then, I would be able to move forward on my project by adding my forked version of react-dropzone -- which would use my forked version of attr-accept added via `yarn add`. This way, I can move forward on my project without waiting for both this project and react-dropzone to publish fixes to these issues to npm.

I don't think it's uncommon to want to be able to move forward in a project that relies on broken dependencies without having to wait for the project to publish a fix. Moreoever, this is a big part of why git dependencies exist in npm/yarn to begin with. 

If you don't want to version the project that way, it's your project, all good. But it's worth pointing out that by doing so, this project is explicitly breaking known intended functionality of the package manager it uses.

The error output from my project from parcel is below:

<details>
```
🚨  [PROJECT_PATH]/node_modules/attr-accept/dist/index.js: [BABEL] [PROJECT_PATH]/node_modules/attr-accept/dist/index.js: Using removed Babel 5 option: [PROJECT_PATH]/node_modules/attr-accept/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error ([PROJECT_PATH]/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions ([PROJECT_PATH]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init ([PROJECT_PATH]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions ([PROJECT_PATH]/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File ([PROJECT_PATH]/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.getParserOptions ([PROJECT_PATH]/node_modules/parcel-bundler/src/assets/JSAsset.js:71:20)
    at <anonymous>
```
</details>

**Comment by ajsharp** [comment]
Also, as you know, I did push two changes to master that you'll need to revert if you disagree with them. They seemed like clear and obvious bug fixes which had been requested by several people on this thread, which is the only reason why I pushed them directly to master. My bad.

I've also opened a PR that fixes the travis build.

**Comment by okonet** [comment]
@ajsharp I'll revert them. Will look at the PR. Thanks!

**Comment by okonet** [comment]
@ajsharp I've rebased and force pushed the master. Please reset next time you update. Thanks for working on the fix.

**Comment by msluther** [comment]
@okonet Why was this issue closed? There still isn't a version of this published with `.babelrc` in `.npmignore`

**Comment by okonet** [comment]
Semantic-release fails but build is passing. I love JS ¯\_(ツ)_/¯

**Comment by ajsharp** [comment]
@okonet Are you building locally or is the failure happening on travis? Looking at the last line of the travis output, i see [this](https://travis-ci.org/okonet/attr-accept/jobs/339619792):  `This run was triggered by a pull request and therefore a new version won't be published.`

If you're having local problems, I've had lots of local build problems as well. I had to blow away node_modules and make sure I was using node 8.9.3 to get my local build working again.

**Comment by okonet** [comment]
CI. I need to authenticate.

**Comment by rkmarks** [comment]
@okonet were you able to update your token for the CI?

**Comment by rkmarks** [comment]
@okonet sorry to prod but the current version for this module still hasn't been published to npm. If you want I can update the CI token for you if you do not have time to maintain this anymore. Please let me know

**Comment by rkmarks** [comment]
Fix has been deployed on v1.1.1 thank you all for your patience 
PR #25
